# Generated by Django 4.0.5 on 2022-06-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_additional_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
