# Generated by Django 4.0.5 on 2022-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_additional_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
